"""initialise

Revision ID: b8754f0e7863
Revises: 
Create Date: 2016-11-13 20:32:22.459105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8754f0e7863'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barnacles_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('barnacles_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=260), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid'),
    sqlite_autoincrement=True
    )
    op.create_table('barnacles_videotags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_barnacles_videotags_tag_id'), 'barnacles_videotags', ['tag_id'], unique=False)
    op.create_index(op.f('ix_barnacles_videotags_video_id'), 'barnacles_videotags', ['video_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barnacles_videotags_video_id'), table_name='barnacles_videotags')
    op.drop_index(op.f('ix_barnacles_videotags_tag_id'), table_name='barnacles_videotags')
    op.drop_table('barnacles_videotags')
    op.drop_table('barnacles_video')
    op.drop_table('barnacles_tag')
    ### end Alembic commands ###
